/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export interface Order {
  'id' : bigint,
  'orderStatus' : OrderStatus,
  'paymentOption' : PaymentOption,
  'name' : string,
  'createdAt' : Time,
  'deliveryTime' : bigint,
  'videoLink' : string,
  'email' : string,
  'style' : string,
  'thumbnailText' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'inProgress' : null };
export type PaymentOption = { 'creditcard' : null } |
  { 'crypto' : null } |
  { 'paypal' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitOrder' : ActorMethod<[Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];