/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PaymentOption = IDL.Variant({
  'creditcard' : IDL.Null,
  'crypto' : IDL.Null,
  'paypal' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'orderStatus' : OrderStatus,
  'paymentOption' : PaymentOption,
  'name' : IDL.Text,
  'createdAt' : Time,
  'deliveryTime' : IDL.Nat,
  'videoLink' : IDL.Text,
  'email' : IDL.Text,
  'style' : IDL.Text,
  'thumbnailText' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitOrder' : IDL.Func([Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PaymentOption = IDL.Variant({
    'creditcard' : IDL.Null,
    'crypto' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'orderStatus' : OrderStatus,
    'paymentOption' : PaymentOption,
    'name' : IDL.Text,
    'createdAt' : Time,
    'deliveryTime' : IDL.Nat,
    'videoLink' : IDL.Text,
    'email' : IDL.Text,
    'style' : IDL.Text,
    'thumbnailText' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitOrder' : IDL.Func([Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };