/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Order {
    id: bigint;
    orderStatus: OrderStatus;
    paymentOption: PaymentOption;
    name: string;
    createdAt: Time;
    deliveryTime: bigint;
    videoLink: string;
    email: string;
    style: string;
    thumbnailText: string;
}
export interface ContactMessage {
    name: string;
    createdAt: Time;
    email: string;
    message: string;
}
export enum OrderStatus {
    pending = "pending",
    delivered = "delivered",
    inProgress = "inProgress"
}
export enum PaymentOption {
    creditcard = "creditcard",
    crypto = "crypto",
    paypal = "paypal"
}
export interface backendInterface {
    getAllContactMessages(): Promise<Array<ContactMessage>>;
    getAllOrders(): Promise<Array<Order>>;
    submitContactMessage(message: ContactMessage): Promise<void>;
    submitOrder(order: Order): Promise<void>;
}
import type { Order as _Order, OrderStatus as _OrderStatus, PaymentOption as _PaymentOption, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactMessages();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0);
            return result;
        }
    }
    async submitOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOrder(to_candid_Order_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOrder(to_candid_Order_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentOption_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentOption): PaymentOption {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    orderStatus: _OrderStatus;
    paymentOption: _PaymentOption;
    name: string;
    createdAt: _Time;
    deliveryTime: bigint;
    videoLink: string;
    email: string;
    style: string;
    thumbnailText: string;
}): {
    id: bigint;
    orderStatus: OrderStatus;
    paymentOption: PaymentOption;
    name: string;
    createdAt: Time;
    deliveryTime: bigint;
    videoLink: string;
    email: string;
    style: string;
    thumbnailText: string;
} {
    return {
        id: value.id,
        orderStatus: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.orderStatus),
        paymentOption: from_candid_PaymentOption_n6(_uploadFile, _downloadFile, value.paymentOption),
        name: value.name,
        createdAt: value.createdAt,
        deliveryTime: value.deliveryTime,
        videoLink: value.videoLink,
        email: value.email,
        style: value.style,
        thumbnailText: value.thumbnailText
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    delivered: null;
} | {
    inProgress: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "inProgress" in value ? OrderStatus.inProgress : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditcard: null;
} | {
    crypto: null;
} | {
    paypal: null;
}): PaymentOption {
    return "creditcard" in value ? PaymentOption.creditcard : "crypto" in value ? PaymentOption.crypto : "paypal" in value ? PaymentOption.paypal : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentOption_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentOption): _PaymentOption {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    orderStatus: OrderStatus;
    paymentOption: PaymentOption;
    name: string;
    createdAt: Time;
    deliveryTime: bigint;
    videoLink: string;
    email: string;
    style: string;
    thumbnailText: string;
}): {
    id: bigint;
    orderStatus: _OrderStatus;
    paymentOption: _PaymentOption;
    name: string;
    createdAt: _Time;
    deliveryTime: bigint;
    videoLink: string;
    email: string;
    style: string;
    thumbnailText: string;
} {
    return {
        id: value.id,
        orderStatus: to_candid_OrderStatus_n10(_uploadFile, _downloadFile, value.orderStatus),
        paymentOption: to_candid_PaymentOption_n12(_uploadFile, _downloadFile, value.paymentOption),
        name: value.name,
        createdAt: value.createdAt,
        deliveryTime: value.deliveryTime,
        videoLink: value.videoLink,
        email: value.email,
        style: value.style,
        thumbnailText: value.thumbnailText
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    delivered: null;
} | {
    inProgress: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentOption): {
    creditcard: null;
} | {
    crypto: null;
} | {
    paypal: null;
} {
    return value == PaymentOption.creditcard ? {
        creditcard: null
    } : value == PaymentOption.crypto ? {
        crypto: null
    } : value == PaymentOption.paypal ? {
        paypal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
